BASE_DIRECTORY: 'train_out_kitti'
EXPERIMENT_NAME: 'topo9_kitti_rigid'
NUM_WORKERS: 8
USE_AMP: False
DEVICE: 'cuda'
DATA:
  PIN_MEMORY: True
  PERSISTENT_WORKERS: True
  PREFETCH_FACTOR: 2
  TOPO_CACHE_ENABLED: True
  TOPO_CACHE_IN_MEMORY: True
  TOPO_CACHE_DIR: 'topo_cache'
MODEL:
  PPWC_SFPC_BN: False
  TOPO_FEAT_DIM: 6
SOLVER:
  BATCH_SIZE: 6
  NUM_EPOCHS: 60
  LEARNING_RATE: 0.001
  SCHEDULER: 'multistep'
  LR_LAMBDA: 0.1
  LR_MILESTONES: [40, 50]
  LOSS_FACTOR: 10.
INPUT:
  SCALE_NORM_FACTOR: 100
AUGMENTATIONS:
  METHOD: 'rigid_one'
  MAX_ROTATION_ANGLE: 10.
  MAX_SCALE_OFFSET: 0.1
  MAX_TRANSLATION: 0.005