BASE_DIRECTORY: 'train_out_kitti_odom'
EXPERIMENT_NAME: 'topo9_kitti_odom'
NUM_WORKERS: 4
USE_AMP: False
DEVICE: 'cuda'
DATA:
  PIN_MEMORY: True
  PERSISTENT_WORKERS: True
  PREFETCH_FACTOR: 2
  TOPO_CACHE_ENABLED: True
  TOPO_CACHE_IN_MEMORY: True
  TOPO_CACHE_DIR: 'topo_cache'
MODEL:
  PPWC_SFPC_BN: False
  TOPO_FEAT_DIM: 6
SOLVER:
  BATCH_SIZE: 4
  NUM_EPOCHS: 30
  LEARNING_RATE: 0.001
  SCHEDULER: 'multistep'
  LR_LAMBDA: 0.1
  LR_MILESTONES: [40, 50]
  CHECKPOINT_INTERVAL: 10
  LOSS_FACTOR: 10.0
INPUT:
  SCALE_NORM_FACTOR: 100
AUGMENTATIONS:
  METHOD: ''
