from yacs.config import CfgNode as CN

_C = CN()

_C.BASE_DIRECTORY = "results/"
_C.EXPERIMENT_NAME = ""
_C.NUM_WORKERS = 8
_C.DEVICE = 'cuda'
_C.USE_AMP = True

_C.DATA = CN()
_C.DATA.PIN_MEMORY = True
_C.DATA.PERSISTENT_WORKERS = True
_C.DATA.PREFETCH_FACTOR = 2
_C.DATA.TOPO_CACHE_ENABLED = True
_C.DATA.TOPO_CACHE_IN_MEMORY = True
_C.DATA.TOPO_CACHE_DIR = 'topo_cache'
_C.DATA.TOPO_CACHE_VERSION = 'v2'
_C.DATA.TOPO_NORMALIZATION = 'none'
_C.DATA.TOPO_STATS_PATH = ''
_C.DATA.TOPO_NORM_EPS = 1e-6

_C.MODEL = CN()
_C.MODEL.PPWC_SFPC_BN = False
# Added for topological feature ablation
_C.MODEL.TOPO_FEAT_DIM = 0

_C.SOLVER = CN()
_C.SOLVER.LEARNING_RATE = 0.001
_C.SOLVER.NUM_EPOCHS = 100
_C.SOLVER.SCHEDULER = 'multistep'
_C.SOLVER.LR_MILESTONES = []
_C.SOLVER.LR_LAMBDA = 0.1
_C.SOLVER.BATCH_SIZE = 8
_C.SOLVER.CHECKPOINT_INTERVAL = 20
_C.SOLVER.LOSS_FACTOR = 10.
_C.SOLVER.TOPO_LOSS_WEIGHT = 0.0
_C.SOLVER.TOPO_LOSS_WARMUP_EPOCHS = 0
_C.SOLVER.TOPO_LOSS_K = 16
_C.SOLVER.TOPO_LOSS_NUM_ANCHORS = 512
_C.SOLVER.TOPO_LOSS_QUERY_CHUNK_SIZE = 128
_C.SOLVER.TOPO_LOSS_BETA = 0.01


_C.INPUT = CN()
_C.INPUT.SCALE_NORM_FACTOR = 100


_C.AUGMENTATIONS = CN()
_C.AUGMENTATIONS.METHOD = ''
_C.AUGMENTATIONS.MAX_ROTATION_ANGLE = 0.
_C.AUGMENTATIONS.MAX_SCALE_OFFSET = 0.
_C.AUGMENTATIONS.MAX_TRANSLATION = 0.
_C.AUGMENTATIONS.NUM_CONTROL_POINTS_LOCAL = 500
_C.AUGMENTATIONS.MAX_CONTROL_SHIFT_LOCAL = 0.03
_C.AUGMENTATIONS.KERNEL_STD_LOCAL = 0.08
_C.AUGMENTATIONS.GLOBAL_GRID_SPACING = 0.9
_C.AUGMENTATIONS.MAX_CONTROL_SHIFT_GLOBAL = 0.25
_C.AUGMENTATIONS.KERNEL_STD_GLOBAL = 0.25


def get_cfg_defaults():
    return _C.clone()
